server:
  port: 8761
spring:
  application:
    name: eureka-server

eureka:
  client:
    # Eureka ??? Client ????? ???? ??? ? ??. ????? ?? ?? ????? ??
    register-with-eureka: false
    # ?? ????? ?????? ???? ??? ?? (fail over ?? ??)
    fetch-registry: false
  # ?? ?? ??? ??? ?? ??
  server:
    waitTimeInMsWhenSyncEmpty: 0