spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
      username: sa
      password:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 10
